[package]
name = "anna_ivanovna"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1.34.3"
chrono = "0.4.35"
rust_decimal_macros = "1.34.2"
uuid = { version = "1.8.0", features = ["v4"] }
serde = "1.0.210"
serde_yaml = "0.9.34"
